trigger:
- main

pool:
  name: docker_agent

variables:
  BuildConfiguration

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build .NET Core App'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'
    modifyOutputPath: $(Build.ArtifactStagingDirectory)

- task: DotNetCoreCLI@2
  displayName: 'Run .NET Core App'
  inputs:
    command: 'run'
    projects: '**/*.csproj'
  
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
