trigger:
- main

pool:
  name: docker_agent

variables:
  BuildConfiguration: Release
  versioning: '1.0.0'  # Set your version number here

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build .NET Core App'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'


- task: DotNetCoreCLI@2
  displayName: 'Run .NET Core App'
  inputs:
    command: 'run'
    projects: '**/*.csproj'

- script: |
    echo "Incrementing version number only if CI steps are successful..."
    echo "##vso[task.setvariable variable=versioning]1.0.$(Build.BuildId)"
  displayName: 'Increment Version Number'

- task: NuGetCommand@2
  displayName: 'Pack NuGet Package'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'versioning'




