trigger:
- main

pool:
  name: docker_agent
  demands:
  - agent.name -equals agent.net

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build .NET Core App'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'

- script: dotnet run --project _netHelloWorld
  displayName: 'Run .NET Core App'
