trigger:
- main

pool:
  name: docker_agent

variables:
  BuildConfiguration: Release

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build .NET Core App'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'
    packDirectory: '$(Build.ArtifactStagingDirectory)' # string. Alias: outputDir. Optional. Use when command = pack. Package Folder. Default: $(Build.ArtifactStagingDirectory).


- task: DotNetCoreCLI@2
  displayName: 'Run .NET Core App'
  inputs:
    command: 'run'
    projects: '**/*.csproj'
  
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
